# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 23:38
from __future__ import unicode_literals

from django.db import migrations
from brain.removalist.operations import CreateTableDuplication


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        CreateTableDuplication('sample_app.OldUser', 'sample_app.NewUser')]
